### PR TITLE
LookAt Created and MoveTo with TruncatePath

### PR DESCRIPTION
**Pull request by aaggj**
Created LookAt and MoveTo with distance tolerance via subtree with ComputePathToPose, TruncatePath and FollowPath

### CODE REVIEW

**Comment by Juancams** [comment]
Add attention_system to .repos pls

**Comment by fmrico** [comment]
Please, add a description to every PR

**Comment by Juancams** [comment]
In line 41 you are loading the wrong xml, you have to use this
```c
std::string pkgpath = ament_index_cpp::get_package_share_directory("bt_test");
std::string xml_file = pkgpath + "/bt_xml/moveto.xml";
```

When running that bt I receive the following error
```bash
juanca@cachorro:~/ros/coresense_ws$ ros2 run bt_test move_to_test
terminate called after throwing an instance of 'BT::RuntimeError'
  what():  Error at line 3: -> Node not recognized: PipelineSequence
[ros2run]: Aborted
```

Is it my fault? I am doing something wrong?

**Comment by Juancams** [comment]
I have tried attention but I have to launch the ros2 node run bt_test look_at_test several times until it decides to target the tf

**Pull request merged**
